### ISSUE TITLE
List of "routes" declared in the app

### ISSUE THREAD

**Issue by rhymes** [soveran/cuba#65]
It would be awesome to have a sort of `rake routes` to have the list of the defined URL that the Cuba app can match on.

If you give me some pointers into the code I can try to code it myself and submit a PR.

Thanks!

**Comment by soveran** [comment]
Hey @rhymes, I'm afraid it's a very difficult (or impossible!) task. In Rails, the routes are compiled and can be observed later. What you get in that list is something like the following:

```
users GET    /users(.:format)          users#index
      POST   /users(.:format)          users#create
```
In that list, you only see the `REQUEST_METHOD` and the path matcher. In Cuba, you can match against anything, and you can nest the routes in different ways. Because of that, building a list of routes is as difficult as building a list of possible matches for an arbitrary regular expression. As that list is infinite, there's no simple way to create a user friendly representation. I won't close the issue right away so that others can participate and share their point of view.

**Comment by rhymes** [comment]
@soveran I understand. Thanks for the explanation. 

Do you think that keeping a compiled list of the matchers benefits speed in Cuba's case? Maybe we can just print those.

**Comment by F-3r** [comment]
This is perhaps kind of a "caveman approach", but perhaps is transformable into a good idea?

We ussually have our cuba apps under `/apps` dir. Using grep like:

`grep -rn "on\ .*do " apps/*`

we get:

```grep
#...
apps/app.rb:584:              on put, ':id/edit' do |id|
apps/app.rb:604:              on ':id/configuration' do |id|
apps/app.rb:624:                on put, param(:data) do |data|
apps/app.rb:644:                on post, param(:data) do |data|
apps/app.rb:650:              on put, ':id/recover' do |id|
#...
```

Not as fancy as `rake routes`, but definetely faster :P

**Comment by soveran** [comment]
I'm closing this issue, but I recommend reading this thread: https://github.com/soveran/syro/issues/18
